version: "2"
services:
  sut:
    image: appcelerator/sut
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test:/usr/local/test
    command: [/usr/local/test/docker-compose.test.sh]
