version: "2"
services:
  alpine:
    image: appcelerator/alpine
    build:
      context: .
      dockerfile: Dockerfile
    command: ["true"]
  sut:
    image: appcelerator/sut
    depends_on:
      - alpine
    build:
      context: .
      dockerfile: Dockerfile.sut
    command: ["/usr/local/sut/sut.sh"]
